// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elasticsearch.proto

package observability.schema;

public final class Elasticsearch {
  private Elasticsearch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ElasticsearchFieldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:observability.schema.ElasticsearchField)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *boolean
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     *boolean
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>bool store = 2;</code>
     * @return The store.
     */
    boolean getStore();

    /**
     * <code>bool index = 3;</code>
     * @return The index.
     */
    boolean getIndex();

    /**
     * <code>bool doc_values = 4;</code>
     * @return The docValues.
     */
    boolean getDocValues();
  }
  /**
   * Protobuf type {@code observability.schema.ElasticsearchField}
   */
  public static final class ElasticsearchField extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:observability.schema.ElasticsearchField)
      ElasticsearchFieldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ElasticsearchField.newBuilder() to construct.
    private ElasticsearchField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ElasticsearchField() {
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ElasticsearchField();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ElasticsearchField(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 16: {

              store_ = input.readBool();
              break;
            }
            case 24: {

              index_ = input.readBool();
              break;
            }
            case 32: {

              docValues_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchField_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              observability.schema.Elasticsearch.ElasticsearchField.class, observability.schema.Elasticsearch.ElasticsearchField.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     *boolean
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *boolean
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STORE_FIELD_NUMBER = 2;
    private boolean store_;
    /**
     * <code>bool store = 2;</code>
     * @return The store.
     */
    @java.lang.Override
    public boolean getStore() {
      return store_;
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private boolean index_;
    /**
     * <code>bool index = 3;</code>
     * @return The index.
     */
    @java.lang.Override
    public boolean getIndex() {
      return index_;
    }

    public static final int DOC_VALUES_FIELD_NUMBER = 4;
    private boolean docValues_;
    /**
     * <code>bool doc_values = 4;</code>
     * @return The docValues.
     */
    @java.lang.Override
    public boolean getDocValues() {
      return docValues_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (store_ != false) {
        output.writeBool(2, store_);
      }
      if (index_ != false) {
        output.writeBool(3, index_);
      }
      if (docValues_ != false) {
        output.writeBool(4, docValues_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (store_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, store_);
      }
      if (index_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, index_);
      }
      if (docValues_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, docValues_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof observability.schema.Elasticsearch.ElasticsearchField)) {
        return super.equals(obj);
      }
      observability.schema.Elasticsearch.ElasticsearchField other = (observability.schema.Elasticsearch.ElasticsearchField) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (getStore()
          != other.getStore()) return false;
      if (getIndex()
          != other.getIndex()) return false;
      if (getDocValues()
          != other.getDocValues()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + STORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStore());
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIndex());
      hash = (37 * hash) + DOC_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDocValues());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static observability.schema.Elasticsearch.ElasticsearchField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(observability.schema.Elasticsearch.ElasticsearchField prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code observability.schema.ElasticsearchField}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:observability.schema.ElasticsearchField)
        observability.schema.Elasticsearch.ElasticsearchFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchField_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchField_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                observability.schema.Elasticsearch.ElasticsearchField.class, observability.schema.Elasticsearch.ElasticsearchField.Builder.class);
      }

      // Construct using observability.schema.Elasticsearch.ElasticsearchField.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        store_ = false;

        index_ = false;

        docValues_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchField_descriptor;
      }

      @java.lang.Override
      public observability.schema.Elasticsearch.ElasticsearchField getDefaultInstanceForType() {
        return observability.schema.Elasticsearch.ElasticsearchField.getDefaultInstance();
      }

      @java.lang.Override
      public observability.schema.Elasticsearch.ElasticsearchField build() {
        observability.schema.Elasticsearch.ElasticsearchField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public observability.schema.Elasticsearch.ElasticsearchField buildPartial() {
        observability.schema.Elasticsearch.ElasticsearchField result = new observability.schema.Elasticsearch.ElasticsearchField(this);
        result.type_ = type_;
        result.store_ = store_;
        result.index_ = index_;
        result.docValues_ = docValues_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof observability.schema.Elasticsearch.ElasticsearchField) {
          return mergeFrom((observability.schema.Elasticsearch.ElasticsearchField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(observability.schema.Elasticsearch.ElasticsearchField other) {
        if (other == observability.schema.Elasticsearch.ElasticsearchField.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getStore() != false) {
          setStore(other.getStore());
        }
        if (other.getIndex() != false) {
          setIndex(other.getIndex());
        }
        if (other.getDocValues() != false) {
          setDocValues(other.getDocValues());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        observability.schema.Elasticsearch.ElasticsearchField parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (observability.schema.Elasticsearch.ElasticsearchField) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *boolean
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *boolean
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *boolean
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *boolean
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *boolean
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private boolean store_ ;
      /**
       * <code>bool store = 2;</code>
       * @return The store.
       */
      @java.lang.Override
      public boolean getStore() {
        return store_;
      }
      /**
       * <code>bool store = 2;</code>
       * @param value The store to set.
       * @return This builder for chaining.
       */
      public Builder setStore(boolean value) {
        
        store_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool store = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStore() {
        
        store_ = false;
        onChanged();
        return this;
      }

      private boolean index_ ;
      /**
       * <code>bool index = 3;</code>
       * @return The index.
       */
      @java.lang.Override
      public boolean getIndex() {
        return index_;
      }
      /**
       * <code>bool index = 3;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(boolean value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool index = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = false;
        onChanged();
        return this;
      }

      private boolean docValues_ ;
      /**
       * <code>bool doc_values = 4;</code>
       * @return The docValues.
       */
      @java.lang.Override
      public boolean getDocValues() {
        return docValues_;
      }
      /**
       * <code>bool doc_values = 4;</code>
       * @param value The docValues to set.
       * @return This builder for chaining.
       */
      public Builder setDocValues(boolean value) {
        
        docValues_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool doc_values = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDocValues() {
        
        docValues_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:observability.schema.ElasticsearchField)
    }

    // @@protoc_insertion_point(class_scope:observability.schema.ElasticsearchField)
    private static final observability.schema.Elasticsearch.ElasticsearchField DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new observability.schema.Elasticsearch.ElasticsearchField();
    }

    public static observability.schema.Elasticsearch.ElasticsearchField getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ElasticsearchField>
        PARSER = new com.google.protobuf.AbstractParser<ElasticsearchField>() {
      @java.lang.Override
      public ElasticsearchField parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ElasticsearchField(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ElasticsearchField> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ElasticsearchField> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public observability.schema.Elasticsearch.ElasticsearchField getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ElasticsearchFieldStringOrBuilder extends
      // @@protoc_insertion_point(interface_extends:observability.schema.ElasticsearchFieldString)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *keyword or text
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     *keyword or text
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>bool store = 2;</code>
     * @return The store.
     */
    boolean getStore();

    /**
     * <code>bool index = 3;</code>
     * @return The index.
     */
    boolean getIndex();

    /**
     * <code>bool doc_values = 4;</code>
     * @return The docValues.
     */
    boolean getDocValues();

    /**
     * <code>bool norms = 5;</code>
     * @return The norms.
     */
    boolean getNorms();
  }
  /**
   * Protobuf type {@code observability.schema.ElasticsearchFieldString}
   */
  public static final class ElasticsearchFieldString extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:observability.schema.ElasticsearchFieldString)
      ElasticsearchFieldStringOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ElasticsearchFieldString.newBuilder() to construct.
    private ElasticsearchFieldString(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ElasticsearchFieldString() {
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ElasticsearchFieldString();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ElasticsearchFieldString(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 16: {

              store_ = input.readBool();
              break;
            }
            case 24: {

              index_ = input.readBool();
              break;
            }
            case 32: {

              docValues_ = input.readBool();
              break;
            }
            case 40: {

              norms_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchFieldString_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchFieldString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              observability.schema.Elasticsearch.ElasticsearchFieldString.class, observability.schema.Elasticsearch.ElasticsearchFieldString.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     *keyword or text
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *keyword or text
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STORE_FIELD_NUMBER = 2;
    private boolean store_;
    /**
     * <code>bool store = 2;</code>
     * @return The store.
     */
    @java.lang.Override
    public boolean getStore() {
      return store_;
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private boolean index_;
    /**
     * <code>bool index = 3;</code>
     * @return The index.
     */
    @java.lang.Override
    public boolean getIndex() {
      return index_;
    }

    public static final int DOC_VALUES_FIELD_NUMBER = 4;
    private boolean docValues_;
    /**
     * <code>bool doc_values = 4;</code>
     * @return The docValues.
     */
    @java.lang.Override
    public boolean getDocValues() {
      return docValues_;
    }

    public static final int NORMS_FIELD_NUMBER = 5;
    private boolean norms_;
    /**
     * <code>bool norms = 5;</code>
     * @return The norms.
     */
    @java.lang.Override
    public boolean getNorms() {
      return norms_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (store_ != false) {
        output.writeBool(2, store_);
      }
      if (index_ != false) {
        output.writeBool(3, index_);
      }
      if (docValues_ != false) {
        output.writeBool(4, docValues_);
      }
      if (norms_ != false) {
        output.writeBool(5, norms_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (store_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, store_);
      }
      if (index_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, index_);
      }
      if (docValues_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, docValues_);
      }
      if (norms_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, norms_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof observability.schema.Elasticsearch.ElasticsearchFieldString)) {
        return super.equals(obj);
      }
      observability.schema.Elasticsearch.ElasticsearchFieldString other = (observability.schema.Elasticsearch.ElasticsearchFieldString) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (getStore()
          != other.getStore()) return false;
      if (getIndex()
          != other.getIndex()) return false;
      if (getDocValues()
          != other.getDocValues()) return false;
      if (getNorms()
          != other.getNorms()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + STORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStore());
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIndex());
      hash = (37 * hash) + DOC_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDocValues());
      hash = (37 * hash) + NORMS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNorms());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static observability.schema.Elasticsearch.ElasticsearchFieldString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(observability.schema.Elasticsearch.ElasticsearchFieldString prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code observability.schema.ElasticsearchFieldString}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:observability.schema.ElasticsearchFieldString)
        observability.schema.Elasticsearch.ElasticsearchFieldStringOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchFieldString_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchFieldString_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                observability.schema.Elasticsearch.ElasticsearchFieldString.class, observability.schema.Elasticsearch.ElasticsearchFieldString.Builder.class);
      }

      // Construct using observability.schema.Elasticsearch.ElasticsearchFieldString.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        store_ = false;

        index_ = false;

        docValues_ = false;

        norms_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return observability.schema.Elasticsearch.internal_static_observability_schema_ElasticsearchFieldString_descriptor;
      }

      @java.lang.Override
      public observability.schema.Elasticsearch.ElasticsearchFieldString getDefaultInstanceForType() {
        return observability.schema.Elasticsearch.ElasticsearchFieldString.getDefaultInstance();
      }

      @java.lang.Override
      public observability.schema.Elasticsearch.ElasticsearchFieldString build() {
        observability.schema.Elasticsearch.ElasticsearchFieldString result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public observability.schema.Elasticsearch.ElasticsearchFieldString buildPartial() {
        observability.schema.Elasticsearch.ElasticsearchFieldString result = new observability.schema.Elasticsearch.ElasticsearchFieldString(this);
        result.type_ = type_;
        result.store_ = store_;
        result.index_ = index_;
        result.docValues_ = docValues_;
        result.norms_ = norms_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof observability.schema.Elasticsearch.ElasticsearchFieldString) {
          return mergeFrom((observability.schema.Elasticsearch.ElasticsearchFieldString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(observability.schema.Elasticsearch.ElasticsearchFieldString other) {
        if (other == observability.schema.Elasticsearch.ElasticsearchFieldString.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getStore() != false) {
          setStore(other.getStore());
        }
        if (other.getIndex() != false) {
          setIndex(other.getIndex());
        }
        if (other.getDocValues() != false) {
          setDocValues(other.getDocValues());
        }
        if (other.getNorms() != false) {
          setNorms(other.getNorms());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        observability.schema.Elasticsearch.ElasticsearchFieldString parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (observability.schema.Elasticsearch.ElasticsearchFieldString) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *keyword or text
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *keyword or text
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *keyword or text
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *keyword or text
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *keyword or text
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private boolean store_ ;
      /**
       * <code>bool store = 2;</code>
       * @return The store.
       */
      @java.lang.Override
      public boolean getStore() {
        return store_;
      }
      /**
       * <code>bool store = 2;</code>
       * @param value The store to set.
       * @return This builder for chaining.
       */
      public Builder setStore(boolean value) {
        
        store_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool store = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStore() {
        
        store_ = false;
        onChanged();
        return this;
      }

      private boolean index_ ;
      /**
       * <code>bool index = 3;</code>
       * @return The index.
       */
      @java.lang.Override
      public boolean getIndex() {
        return index_;
      }
      /**
       * <code>bool index = 3;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(boolean value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool index = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = false;
        onChanged();
        return this;
      }

      private boolean docValues_ ;
      /**
       * <code>bool doc_values = 4;</code>
       * @return The docValues.
       */
      @java.lang.Override
      public boolean getDocValues() {
        return docValues_;
      }
      /**
       * <code>bool doc_values = 4;</code>
       * @param value The docValues to set.
       * @return This builder for chaining.
       */
      public Builder setDocValues(boolean value) {
        
        docValues_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool doc_values = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDocValues() {
        
        docValues_ = false;
        onChanged();
        return this;
      }

      private boolean norms_ ;
      /**
       * <code>bool norms = 5;</code>
       * @return The norms.
       */
      @java.lang.Override
      public boolean getNorms() {
        return norms_;
      }
      /**
       * <code>bool norms = 5;</code>
       * @param value The norms to set.
       * @return This builder for chaining.
       */
      public Builder setNorms(boolean value) {
        
        norms_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool norms = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNorms() {
        
        norms_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:observability.schema.ElasticsearchFieldString)
    }

    // @@protoc_insertion_point(class_scope:observability.schema.ElasticsearchFieldString)
    private static final observability.schema.Elasticsearch.ElasticsearchFieldString DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new observability.schema.Elasticsearch.ElasticsearchFieldString();
    }

    public static observability.schema.Elasticsearch.ElasticsearchFieldString getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ElasticsearchFieldString>
        PARSER = new com.google.protobuf.AbstractParser<ElasticsearchFieldString>() {
      @java.lang.Override
      public ElasticsearchFieldString parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ElasticsearchFieldString(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ElasticsearchFieldString> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ElasticsearchFieldString> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public observability.schema.Elasticsearch.ElasticsearchFieldString getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_observability_schema_ElasticsearchField_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_observability_schema_ElasticsearchField_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_observability_schema_ElasticsearchFieldString_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_observability_schema_ElasticsearchFieldString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023elasticsearch.proto\022\024observability.sch" +
      "ema\"T\n\022ElasticsearchField\022\014\n\004type\030\001 \001(\t\022" +
      "\r\n\005store\030\002 \001(\010\022\r\n\005index\030\003 \001(\010\022\022\n\ndoc_val" +
      "ues\030\004 \001(\010\"i\n\030ElasticsearchFieldString\022\014\n" +
      "\004type\030\001 \001(\t\022\r\n\005store\030\002 \001(\010\022\r\n\005index\030\003 \001(" +
      "\010\022\022\n\ndoc_values\030\004 \001(\010\022\r\n\005norms\030\005 \001(\010b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_observability_schema_ElasticsearchField_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_observability_schema_ElasticsearchField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_observability_schema_ElasticsearchField_descriptor,
        new java.lang.String[] { "Type", "Store", "Index", "DocValues", });
    internal_static_observability_schema_ElasticsearchFieldString_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_observability_schema_ElasticsearchFieldString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_observability_schema_ElasticsearchFieldString_descriptor,
        new java.lang.String[] { "Type", "Store", "Index", "DocValues", "Norms", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
