// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: observabilitySchema.proto

package observability.schema;

public final class ObservabilitySchemaOuterClass {
  private ObservabilitySchemaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(observability.schema.ObservabilitySchemaOuterClass.elasticsearchField);
    registry.add(observability.schema.ObservabilitySchemaOuterClass.elasticsearchFieldString);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ObservabilitySchemaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:observability.schema.ObservabilitySchema)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>int32 port = 2 [(.observability.schema.elasticsearch_field) = { ... }</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code observability.schema.ObservabilitySchema}
   */
  public static final class ObservabilitySchema extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:observability.schema.ObservabilitySchema)
      ObservabilitySchemaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ObservabilitySchema.newBuilder() to construct.
    private ObservabilitySchema(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObservabilitySchema() {
      userId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ObservabilitySchema();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ObservabilitySchema(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return observability.schema.ObservabilitySchemaOuterClass.internal_static_observability_schema_ObservabilitySchema_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return observability.schema.ObservabilitySchemaOuterClass.internal_static_observability_schema_ObservabilitySchema_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema.class, observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>int32 port = 2 [(.observability.schema.elasticsearch_field) = { ... }</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema)) {
        return super.equals(obj);
      }
      observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema other = (observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code observability.schema.ObservabilitySchema}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:observability.schema.ObservabilitySchema)
        observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchemaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return observability.schema.ObservabilitySchemaOuterClass.internal_static_observability_schema_ObservabilitySchema_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return observability.schema.ObservabilitySchemaOuterClass.internal_static_observability_schema_ObservabilitySchema_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema.class, observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema.Builder.class);
      }

      // Construct using observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return observability.schema.ObservabilitySchemaOuterClass.internal_static_observability_schema_ObservabilitySchema_descriptor;
      }

      @java.lang.Override
      public observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema getDefaultInstanceForType() {
        return observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema.getDefaultInstance();
      }

      @java.lang.Override
      public observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema build() {
        observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema buildPartial() {
        observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema result = new observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema(this);
        result.userId_ = userId_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema) {
          return mergeFrom((observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema other) {
        if (other == observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1 [(.observability.schema.elasticsearch_field_string) = { ... }</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2 [(.observability.schema.elasticsearch_field) = { ... }</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2 [(.observability.schema.elasticsearch_field) = { ... }</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2 [(.observability.schema.elasticsearch_field) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:observability.schema.ObservabilitySchema)
    }

    // @@protoc_insertion_point(class_scope:observability.schema.ObservabilitySchema)
    private static final observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema();
    }

    public static observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObservabilitySchema>
        PARSER = new com.google.protobuf.AbstractParser<ObservabilitySchema>() {
      @java.lang.Override
      public ObservabilitySchema parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObservabilitySchema(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ObservabilitySchema> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ObservabilitySchema> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public observability.schema.ObservabilitySchemaOuterClass.ObservabilitySchema getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ELASTICSEARCH_FIELD_FIELD_NUMBER = 5001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      observability.schema.Elasticsearch.ElasticsearchField> elasticsearchField = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        observability.schema.Elasticsearch.ElasticsearchField.class,
        observability.schema.Elasticsearch.ElasticsearchField.getDefaultInstance());
  public static final int ELASTICSEARCH_FIELD_STRING_FIELD_NUMBER = 5002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      observability.schema.Elasticsearch.ElasticsearchFieldString> elasticsearchFieldString = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        observability.schema.Elasticsearch.ElasticsearchFieldString.class,
        observability.schema.Elasticsearch.ElasticsearchFieldString.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_observability_schema_ObservabilitySchema_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_observability_schema_ObservabilitySchema_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031observabilitySchema.proto\022\024observabili" +
      "ty.schema\032\023elasticsearch.proto\032 google/p" +
      "rotobuf/descriptor.proto\"j\n\023Observabilit" +
      "ySchema\022*\n\007user_id\030\001 \001(\tB\031\322\270\002\t\n\007keyword\322" +
      "\270\002\002\030\001\322\270\002\002 \001\022\'\n\004port\030\002 \001(\005B\031\312\270\002\t\n\007integer" +
      "\312\270\002\002\030\001\312\270\002\002 \001:e\n\023elasticsearch_field\022\035.go" +
      "ogle.protobuf.FieldOptions\030\211\' \001(\0132(.obse" +
      "rvability.schema.ElasticsearchField:r\n\032e" +
      "lasticsearch_field_string\022\035.google.proto" +
      "buf.FieldOptions\030\212\' \001(\0132..observability." +
      "schema.ElasticsearchFieldStringb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          observability.schema.Elasticsearch.getDescriptor(),
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_observability_schema_ObservabilitySchema_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_observability_schema_ObservabilitySchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_observability_schema_ObservabilitySchema_descriptor,
        new java.lang.String[] { "UserId", "Port", });
    elasticsearchField.internalInit(descriptor.getExtensions().get(0));
    elasticsearchFieldString.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(observability.schema.ObservabilitySchemaOuterClass.elasticsearchField);
    registry.add(observability.schema.ObservabilitySchemaOuterClass.elasticsearchFieldString);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    observability.schema.Elasticsearch.getDescriptor();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
