// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: elasticsearch.proto

package observability_schema

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ElasticsearchField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` //boolean
	Store     bool   `protobuf:"varint,2,opt,name=store,proto3" json:"store,omitempty"`
	Index     bool   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	DocValues bool   `protobuf:"varint,4,opt,name=doc_values,json=docValues,proto3" json:"doc_values,omitempty"`
}

func (x *ElasticsearchField) Reset() {
	*x = ElasticsearchField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elasticsearch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElasticsearchField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticsearchField) ProtoMessage() {}

func (x *ElasticsearchField) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticsearchField.ProtoReflect.Descriptor instead.
func (*ElasticsearchField) Descriptor() ([]byte, []int) {
	return file_elasticsearch_proto_rawDescGZIP(), []int{0}
}

func (x *ElasticsearchField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ElasticsearchField) GetStore() bool {
	if x != nil {
		return x.Store
	}
	return false
}

func (x *ElasticsearchField) GetIndex() bool {
	if x != nil {
		return x.Index
	}
	return false
}

func (x *ElasticsearchField) GetDocValues() bool {
	if x != nil {
		return x.DocValues
	}
	return false
}

type ElasticsearchFieldString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` //keyword or text
	Store     bool   `protobuf:"varint,2,opt,name=store,proto3" json:"store,omitempty"`
	Index     bool   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	DocValues bool   `protobuf:"varint,4,opt,name=doc_values,json=docValues,proto3" json:"doc_values,omitempty"`
	Norms     bool   `protobuf:"varint,5,opt,name=norms,proto3" json:"norms,omitempty"`
}

func (x *ElasticsearchFieldString) Reset() {
	*x = ElasticsearchFieldString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elasticsearch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElasticsearchFieldString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElasticsearchFieldString) ProtoMessage() {}

func (x *ElasticsearchFieldString) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElasticsearchFieldString.ProtoReflect.Descriptor instead.
func (*ElasticsearchFieldString) Descriptor() ([]byte, []int) {
	return file_elasticsearch_proto_rawDescGZIP(), []int{1}
}

func (x *ElasticsearchFieldString) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ElasticsearchFieldString) GetStore() bool {
	if x != nil {
		return x.Store
	}
	return false
}

func (x *ElasticsearchFieldString) GetIndex() bool {
	if x != nil {
		return x.Index
	}
	return false
}

func (x *ElasticsearchFieldString) GetDocValues() bool {
	if x != nil {
		return x.DocValues
	}
	return false
}

func (x *ElasticsearchFieldString) GetNorms() bool {
	if x != nil {
		return x.Norms
	}
	return false
}

var File_elasticsearch_proto protoreflect.FileDescriptor

var file_elasticsearch_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x73, 0x0a, 0x12, 0x45,
	0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x8f, 0x01, 0x0a, 0x18, 0x45, 0x6c, 0x61, 0x73, 0x74, 0x69, 0x63, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x6f, 0x63, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6e, 0x6f, 0x72,
	0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_elasticsearch_proto_rawDescOnce sync.Once
	file_elasticsearch_proto_rawDescData = file_elasticsearch_proto_rawDesc
)

func file_elasticsearch_proto_rawDescGZIP() []byte {
	file_elasticsearch_proto_rawDescOnce.Do(func() {
		file_elasticsearch_proto_rawDescData = protoimpl.X.CompressGZIP(file_elasticsearch_proto_rawDescData)
	})
	return file_elasticsearch_proto_rawDescData
}

var file_elasticsearch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_elasticsearch_proto_goTypes = []interface{}{
	(*ElasticsearchField)(nil),       // 0: observability.schema.ElasticsearchField
	(*ElasticsearchFieldString)(nil), // 1: observability.schema.ElasticsearchFieldString
}
var file_elasticsearch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_elasticsearch_proto_init() }
func file_elasticsearch_proto_init() {
	if File_elasticsearch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_elasticsearch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElasticsearchField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elasticsearch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElasticsearchFieldString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_elasticsearch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elasticsearch_proto_goTypes,
		DependencyIndexes: file_elasticsearch_proto_depIdxs,
		MessageInfos:      file_elasticsearch_proto_msgTypes,
	}.Build()
	File_elasticsearch_proto = out.File
	file_elasticsearch_proto_rawDesc = nil
	file_elasticsearch_proto_goTypes = nil
	file_elasticsearch_proto_depIdxs = nil
}
